version = "1.1.13"

[format]
# Deduplicate icons if enable.
# A superscripted counter will be added.
# dedup = true
# dedup_inactive_fullscreen = false # dedup more
# window delimiter
delim = " "
# max_clients = 30 # you should not need this

# available formatter:
# {counter_sup} - superscripted count of clients on the workspace, and simple {counter}, {delim}
# {icon}, {client}
# workspace formatter
# workspace = "{id}:{delim}{clients}{delim}" # {id}, {delim} and {clients} are supported
# workspace_empty = "{id}"                   # {id}, {delim} and {clients} are supported
# client formatter
client = "{icon}{delim}"
client_active = "<span foreground='lightblue'>{icon}</span>"

# deduplicate client formatter
# client_fullscreen = "[{icon}]"
# client_dup = "{client}{counter_sup}"
# client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused}"
# client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused}"

[class]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"DEFAULT" = ""
"(?i)Kitty" = ""
'discord' = ''
'Brave-browser' = ''
'Code' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'steam' = ''
'Cider' = ''
'org.remmina.Remmina' = ''
'file-roller' = ''
'Caprine' = '󰈎'
'com.obsproject.Studio' = ''
'thunar' = ''

[class_active]
DEFAULT = ""
#"(?i)ExampleOneTerm" = "<span foreground='red'>{icon}</span>"

# [initial_class]
# "DEFAULT" = " {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

[title_in_class."(?i)Brave-browser"]
'(?i)Youtube' = ''
'(?i)Google' = ''
'(?i)Facebook' = '󰈌'
'(?i)Reddit' = ''
'(?i)r/' = ''
'(?i)Web Player' = ''
'(?i)Zimbra' = ''
'(?i)mail' = ''
"(?i)twitch" = "<span color='purple'>{icon}</span>"

[title_in_class."(?i)kitty"]
'(?i)neomutt' = 'neomutt'
'(?i)nvim' = ''
'.*(?i)vim' = ''
'(?i)openfortivpn' = '󰖂'
'(?i)npm' = ''
'(?i)node' = ''
'(?i)yarn' = ''
# regex captures support is supported
# "emerge: (.+?/.+?)-.*" = "{match1}"

# [title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title."(?i)kitty"]
# "zsh" = "Zsh"
# "(?i)vim" = "neomutt"

# [initial_title_active."(?i)kitty"]
# "zsh" = "*Zsh*"

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
"" = "^$"                          # prevent displaying icon for empty class
"(?i)fcitx" = ".*"                 # will match all title for fcitx
"(?i)TestApp" = ""                 # will match all title for TestApp
aProgram = "^$"                    # will match null title for aProgram
"[Ss]team" = "^(Friends List.*)?$" # will match Steam friends list plus all popups (empty titles)

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"
